-- Malaysian Carbon Emission Factors and Recommendations
-- This file seeds the database with sample data for the carbon footprint calculator

-- IMPORTANT: Before running this script, make sure to:
-- 1. Run: npm run setup-rag (creates tables)
-- 2. Run: npm run populate-emission-factors (populates emission factors from CSV data)
-- 3. Then run this script to insert sample recommendations

-- Note: This script inserts sample recommendations into the recommendations_kb table
-- The carbon_emission_factors table is populated separately from existing CSV data

-- Insert sample recommendations with embeddings (embeddings will be generated by the application)
INSERT INTO public.recommendations_kb (category, title, content, context, impact_level, difficulty, cost_impact, tags) VALUES

-- Travel Recommendations
('travel', 'Use Public Transport in KL', 'Switch to LRT, MRT, or buses for daily commuting in Kuala Lumpur. The public transport system is well-connected and significantly reduces emissions compared to private vehicles.', 'Malaysian public transport is reliable and covers most areas in KL. Consider getting a Touch n Go card for convenience.', 'high', 'easy', 'saves_money', '["public_transport", "commuting", "KL", "emissions_reduction"]'),

('travel', 'Carpool for Long Distance Travel', 'Share rides with colleagues or friends for intercity travel. Use platforms like GrabShare or organize carpooling groups for regular routes.', 'Popular for travel between KL, Penang, Johor Bahru. Many Malaysians already practice this for cost savings.', 'medium', 'moderate', 'saves_money', '["carpooling", "long_distance", "cost_saving", "social"]'),

('travel', 'Walk or Cycle for Short Trips', 'For distances under 2km, consider walking or cycling instead of driving. Many Malaysian cities are becoming more pedestrian-friendly.', 'KLCC, Bukit Bintang, and other areas have good pedestrian infrastructure. Consider weather conditions during rainy season.', 'medium', 'easy', 'saves_money', '["walking", "cycling", "short_distance", "health"]'),

-- Household Recommendations
('household', 'Switch to LED Bulbs', 'Replace all incandescent and CFL bulbs with LED bulbs. They use 80% less energy and last much longer, perfect for Malaysian climate.', 'LED bulbs are widely available in Malaysia and work well in hot, humid conditions. Check for SIRIM certification.', 'medium', 'easy', 'saves_money', '["LED", "lighting", "energy_efficiency", "cost_saving"]'),

('household', 'Use Air Conditioning Efficiently', 'Set AC temperature to 24-26°C and use fans to circulate air. Clean filters monthly and consider inverter AC units for better efficiency.', 'Malaysian climate requires AC usage. Inverter ACs are more expensive but save significantly on electricity bills.', 'high', 'easy', 'neutral', '["air_conditioning", "energy_efficiency", "cooling", "maintenance"]'),

('household', 'Install Solar Panels', 'Consider installing solar panels on your roof. Malaysia has excellent solar potential with feed-in tariff programs available.', 'SEDA Malaysia offers feed-in tariff. Many Malaysian homes have suitable roof space for solar installation.', 'high', 'challenging', 'costs_more', '["solar", "renewable_energy", "feed_in_tariff", "investment"]'),

('household', 'Reduce Water Usage', 'Install low-flow showerheads and faucets. Collect rainwater for gardening. Fix leaks immediately to prevent water waste.', 'Malaysia has abundant rainfall. Rainwater harvesting is practical and legal in most areas.', 'medium', 'moderate', 'saves_money', '["water_conservation", "rainwater_harvesting", "low_flow", "maintenance"]'),

-- Food Recommendations
('food', 'Choose Local and Seasonal Foods', 'Buy locally grown fruits and vegetables. Malaysian produce like durian, rambutan, and local vegetables have lower transport emissions.', 'Malaysian markets (pasar) offer fresh local produce. Seasonal fruits are cheaper and more sustainable.', 'medium', 'easy', 'saves_money', '["local_food", "seasonal", "pasar", "fresh_produce"]'),

('food', 'Reduce Meat Consumption', 'Try Meatless Monday or reduce portion sizes. Malaysian cuisine offers many delicious vegetarian options like nasi lemak with tempeh.', 'Malaysian vegetarian food is diverse and flavorful. Many local restaurants offer vegetarian versions of traditional dishes.', 'high', 'moderate', 'saves_money', '["vegetarian", "meat_reduction", "malaysian_cuisine", "health"]'),

('food', 'Minimize Food Waste', 'Plan meals, store food properly, and use leftovers creatively. Malaysian food can be easily repurposed into new dishes.', 'Malaysian cooking often involves batch preparation. Leftover rice can become nasi goreng, curry can be extended with vegetables.', 'medium', 'easy', 'saves_money', '["food_waste", "meal_planning", "leftovers", "malaysian_cooking"]'),

-- Shopping Recommendations
('shopping', 'Buy Second-Hand Items', 'Shop at thrift stores, online marketplaces like Carousell, or local second-hand shops. Many items are in excellent condition.', 'Malaysian second-hand market is growing. Carousell, Mudah.my, and local thrift stores offer good quality items.', 'medium', 'easy', 'saves_money', '["second_hand", "thrift", "reuse", "cost_saving"]'),

('shopping', 'Choose Quality Over Quantity', 'Invest in durable, high-quality items that last longer. This reduces the need for frequent replacements and saves money long-term.', 'Malaysian consumers are becoming more quality-conscious. Look for items with good warranties and reviews.', 'medium', 'moderate', 'neutral', '["quality", "durability", "investment", "long_term"]'),

('shopping', 'Support Local Brands', 'Choose Malaysian-made products when possible. This reduces transport emissions and supports local economy.', 'Many Malaysian brands offer quality products. Look for "Made in Malaysia" labels and support local entrepreneurs.', 'low', 'easy', 'neutral', '["local_brands", "made_in_malaysia", "support_local", "economy"]'),

('shopping', 'Repair Instead of Replace', 'Fix broken items instead of buying new ones. Many repair shops in Malaysia can fix electronics, furniture, and clothing.', 'Malaysian repair culture is strong. Look for local repair shops in shopping centers and residential areas.', 'medium', 'moderate', 'saves_money', '["repair", "maintenance", "local_services", "cost_saving"]'),

-- Additional Energy Recommendations
('household', 'Turn Off Lights and Appliances', 'Turn off all lights and appliances when not in use. This simple habit can significantly reduce your electricity bill and carbon footprint.', 'Malaysian households can save 10-15% on electricity bills by being mindful of standby power consumption. TNB provides energy monitoring tools.', 'medium', 'easy', 'saves_money', '["energy_saving", "standby_power", "electricity_bill", "habits"]'),

('household', 'Set AC Temperature to 24°C', 'Set your air conditioning temperature to 24°C for optimal comfort and energy efficiency. Every degree lower increases energy consumption by 6-8%.', 'Malaysian climate makes AC essential, but 24°C is comfortable for most people. Use fans to circulate air and feel cooler.', 'high', 'easy', 'saves_money', '["air_conditioning", "temperature_setting", "energy_efficiency", "comfort"]'),

('household', 'Use Fans and Open Windows', 'Use ceiling fans and open windows to circulate air naturally. This reduces the need for air conditioning and improves indoor air quality.', 'Malaysian homes often have good cross-ventilation. Morning and evening breezes can significantly reduce AC usage.', 'medium', 'easy', 'saves_money', '["natural_ventilation", "fans", "air_circulation", "indoor_air_quality"]'),

('household', 'Buy 5-Star Energy Efficient Appliances', 'When replacing appliances, choose 5-star energy efficient models. They may cost more initially but save significantly on electricity bills over time.', 'Malaysian SIRIM energy rating system helps identify efficient appliances. Look for the 5-star rating label when shopping.', 'high', 'moderate', 'neutral', '["energy_efficient", "appliances", "sirim_rating", "long_term_savings"]'),

-- Additional Travel Recommendations
('travel', 'Carpool or Take Bus Once a Week', 'Carpool or take public transport to work at least once a week. This reduces traffic congestion and your personal carbon footprint.', 'Malaysian cities have good public transport options. RapidKL, Rapid Penang, and other services offer monthly passes for regular commuters.', 'medium', 'easy', 'saves_money', '["carpooling", "public_transport", "commuting", "traffic_reduction"]'),

('travel', 'Practice Eco-Driving Techniques', 'Practice eco-driving techniques like smooth acceleration, maintaining steady speed, and avoiding sudden braking to improve fuel efficiency by 15-20%.', 'Malaysian traffic conditions make eco-driving challenging but rewarding. Use cruise control on highways and plan routes to avoid traffic jams.', 'medium', 'moderate', 'saves_money', '["eco_driving", "fuel_efficiency", "smooth_driving", "cruise_control"]'),

('travel', 'Consider Electric Vehicle for Next Car', 'When replacing your vehicle, consider buying an electric vehicle. EVs produce zero direct emissions and are becoming more affordable in Malaysia.', 'Malaysian government offers incentives for EV purchases. Charging infrastructure is expanding in major cities like KL, Penang, and Johor.', 'high', 'challenging', 'costs_more', '["electric_vehicle", "zero_emissions", "government_incentives", "charging_infrastructure"]'),

('travel', 'Walk or Cycle to Local Stores', 'Walk or cycle to neighbourhood grocery stores and shops on weekends. This reduces short car trips and provides health benefits.', 'Malaysian cities are becoming more pedestrian-friendly. Many residential areas have good access to local shops and markets.', 'medium', 'easy', 'saves_money', '["walking", "cycling", "local_shopping", "health_benefits"]'),

-- Waste Management Recommendations
('household', 'Bring Reusable Shopping Bags', 'Bring your own reusable bags when shopping. This reduces plastic waste and helps Malaysia move towards a plastic-free future.', 'Malaysian government has implemented plastic bag charges in many states. Reusable bags are widely available and often free with purchases.', 'medium', 'easy', 'saves_money', '["reusable_bags", "plastic_reduction", "shopping", "waste_reduction"]'),

('household', 'Separate and Recycle Household Waste', 'Separate and recycle all household waste. Proper waste segregation helps reduce landfill waste and supports Malaysia''s recycling industry.', 'Malaysian local councils provide recycling bins and collection services. Many shopping malls also have recycling centers.', 'medium', 'easy', 'neutral', '["waste_segregation", "recycling", "landfill_reduction", "local_councils"]'),

('food', 'Eat Moderately and Finish Your Food', 'Eat moderately and take only what you can finish. This reduces food waste and saves money while being mindful of portion sizes.', 'Malaysian portion sizes are often generous. Consider sharing dishes or taking leftovers home from restaurants.', 'medium', 'easy', 'saves_money', '["portion_control", "food_waste", "moderate_eating", "leftovers"]'),

('food', 'Bring Reusable Food Containers', 'Bring your own food and drink containers to avoid single-use plastics. This is especially useful for takeaway meals and drinks.', 'Malaysian food culture includes many takeaway options. Many restaurants now offer discounts for customers who bring their own containers.', 'medium', 'easy', 'saves_money', '["reusable_containers", "takeaway", "single_use_plastic", "restaurant_discounts"]'),

-- Green Lifestyle Recommendations
('food', 'Eat More Local Vegetables', 'Choose to eat more local vegetables and reduce meat consumption. Malaysian vegetables are fresh, affordable, and have lower carbon footprints.', 'Malaysian markets (pasar) offer a wide variety of local vegetables. Traditional Malaysian cuisine already includes many vegetable-based dishes.', 'high', 'moderate', 'saves_money', '["local_vegetables", "meat_reduction", "pasar", "traditional_cuisine"]'),

('shopping', 'Buy Sustainable Green Products', 'Choose to buy sustainable and eco-friendly products and services. Look for green certifications and environmentally responsible companies.', 'Malaysian companies are increasingly offering green products. Look for SIRIM eco-labels and local sustainable brands.', 'medium', 'moderate', 'neutral', '["sustainable_products", "eco_friendly", "green_certifications", "sirim_eco_label"]'),

('travel', 'Walk and Take Stairs', 'Choose to walk and take stairs whenever possible. This reduces elevator and escalator energy use while providing health benefits.', 'Malaysian buildings often have good stair access. Walking between floors is common in many office buildings and shopping centers.', 'low', 'easy', 'saves_money', '["walking", "stairs", "elevator_reduction", "health_benefits"]'),

('household', 'Spread Environmental Awareness', 'Spread the word and encourage others to reduce their carbon footprint. Share knowledge about sustainable practices with family and friends.', 'Malaysian communities are becoming more environmentally conscious. Social media and community groups are great platforms for sharing green tips.', 'low', 'easy', 'neutral', '["environmental_awareness", "community_sharing", "social_media", "green_education"]');
